#!/usr/bin/env bash
# script to install and configure HAproxy on load balancer server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 384725-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 384725-web-02 52.23.177.189 check\n\tserver 384725-web-01 54.160.89.212 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
