#!/usr/bin/env bash
# script to install and configure HAproxy on load balancer server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "$ a\listen 381427-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 381427-web-02 54.160.113.130:80 check\n\tserver 381427-web-01 54.172.114.96:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
