#!/usr/bin/env bash
# Using your debugging skills, find out what’s keeping your Ubuntu
# container’s Nginx installation from listening on port 80. Feel free
# to install whatever tool you need, start and destroy as many containers
# as you need to debug the issue. Then, write a Bash script with the
# minimum number of commands to automate your fix.
# so overall Fixes the docker container so that nginx listens on port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i 's/8080/80/' /etc/nginx/sites-available/default
service nginx stop
pkill nginx
service nginx start
