#!/usr/bin/env bash
# script to fix nginx server
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i 's/8080/80/' /etc/nginx/sites-available/default
