#!/usr/bin/env bash
# This script generates a fictional story based on the content of the /etc/passwd file.

while IFS=: read -r username _ uid gid info home shell; do
    echo "The user $username is part of the $gid gang,"
    echo "lives in $home and rides $shell."
    echo "USER ID's place is protected by the passcode PASSWORD,"
    echo "more info about the user here: $info"
    echo
done < /etc/passwd
